services:
  redis:
    image: redis
    container_name: test_redis
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: test_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    image: test_image
    build:
      context: .
    container_name: test_app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      sh -c " python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 4 hammer_project.wsgi:application"
    ports:
      - "7777:8000"

volumes:
  postgres_data:
